Repository WFP-VAM/prism-app, pull requests merged in 2020-05, with the labels that each got.

#38 🐛 Fix NotFound page in app router
  package.json
  src/components/App/__snapshots__/index.test.tsx.snap
  src/components/App/index.tsx
  yarn.lock
Labels: bug, frontend

#32 🎉 Fetching server dates
  .eslintrc
  package.json
  src/components/MapView/DateSelector/index.tsx
  src/components/MapView/DateSelector/utils.ts
  src/components/MapView/Layers/index.test.tsx
  src/components/MapView/Layers/index.tsx
  src/components/MapView/__snapshots__/index.test.tsx.snap
  src/components/MapView/index.test.tsx
  src/components/MapView/index.tsx
  src/components/NavBar/MenuItem/index.tsx
  src/components/NavBar/__snapshots__/index.test.tsx.snap
  src/components/NavBar/index.tsx
  src/config/indonesia/layers.json
  src/config/prism.json
  src/config/types.ts
  src/context/mapStateSlice.ts
  src/context/serverStateSlice.ts
  src/context/store.ts
  src/custom.d.ts
  src/utils/server-utils.ts
  yarn.lock
Labels: enhancement, frontend

#37 🎉 Add legend box for selected layers
  src/components/MapView/Legends/ColorIndicator/__snapshots__/index.test.tsx.snap
  src/components/MapView/Legends/ColorIndicator/index.test.tsx
  src/components/MapView/Legends/ColorIndicator/index.tsx
  src/components/MapView/Legends/__snapshots__/index.test.tsx.snap
  src/components/MapView/Legends/index.test.tsx
  src/components/MapView/Legends/index.tsx
  src/components/MapView/__snapshots__/index.test.tsx.snap
  src/components/MapView/index.test.tsx
  src/components/MapView/index.tsx
  src/config/layers.json
  src/muiTheme.tsx
Labels: enhancement, frontend

#51 Add tables in leftside drawer
  .eslintrc
  package.json
  public/data/tables/NSO_Animal_Deaths_Annual_Admin1.csv
  public/data/tables/NSO_Bale_Hay_Price_Monthly_Admin1.csv
  public/data/tables/NSO_Poverty_Headcount_Admin1.csv
  public/data/tables/wfp_food_prices_mongolia.csv
  src/components/App/__snapshots__/index.test.tsx.snap
  src/components/App/index.test.tsx
  src/components/App/index.tsx
  src/components/DataDrawer/DataTable/DataTableRow/index.tsx
  src/components/DataDrawer/DataTable/index.tsx
  src/components/DataDrawer/__snapshots__/index.test.tsx.snap
  src/components/DataDrawer/index.test.tsx
  src/components/DataDrawer/index.tsx
  src/components/MapView/Layers/GroundstationLayer/index.tsx
  src/components/NavBar/MenuItem/__snapshots__/index.test.tsx.snap
  src/components/NavBar/MenuItem/index.test.tsx
  src/components/NavBar/MenuItem/index.tsx
  src/components/NavBar/__snapshots__/index.test.tsx.snap
  src/components/NavBar/utils.ts
  src/components/images/icon_impact.png
  src/components/images/icon_table.png
  src/config/layers.json
  src/config/prism.json
  src/config/tables.json
  src/config/types.ts
  src/config/utils.ts
  src/context/layers/groundstation.ts
  src/context/store.ts
  src/context/tableStateSlice.ts
  yarn.lock
Labels: frontend, skills:React

#67 Add Tooltip with reducer
  src/components/MapView/Boundaries/index.tsx
  src/components/MapView/Layers/GroundstationLayer/index.tsx
  src/components/MapView/Layers/ImpactLayer/index.tsx
  src/components/MapView/Layers/NSOLayer/index.tsx
  src/components/MapView/MapTooltip/index.tsx
  src/components/MapView/index.tsx
  src/context/store.ts
  src/context/tooltipStateSlice.ts
Labels: skills:React
