Repository WFP-VAM/prism-app, pull requests merged in 2020-04, with the labels that each got.

#17 🎉 Add date selector
  package.json
  src/components/MapView/DateSelector/__snapshots__/index.test.tsx.snap
  src/components/MapView/DateSelector/index.test.tsx
  src/components/MapView/DateSelector/index.tsx
  src/components/MapView/DateSelector/utils.ts
  src/components/MapView/Layers/index.tsx
  src/components/MapView/__snapshots__/index.test.tsx.snap
  src/components/MapView/index.test.tsx
  src/components/MapView/index.tsx
  src/components/NavBar/MenuItem/index.tsx
  src/context/filters/filtersSlice.ts
  src/context/mapStateSlice.ts
  src/context/store.ts
  src/muiTheme.tsx
  yarn.lock
Labels: enhancement, frontend

#18 🔧 Firebase config
  .firebaserc
  .gitignore
  firebase.json
  package.json
  src/components/404Page/__snapshots__/index.test.tsx.snap
  src/components/404Page/index.test.tsx
  src/components/404Page/index.tsx
  src/components/App/__snapshots__/index.test.tsx.snap
  src/components/App/index.test.tsx
  src/components/App/index.tsx
  src/components/NavBar/index.tsx
  src/components/images/wfp_logo.png
  src/config/layers.json
  src/muiTheme.tsx
  yarn.lock
Labels: enhancement

#25 Use selected startDate in layer query
  src/components/MapView/Layers/index.tsx
  src/components/MapView/index.test.tsx
  src/components/MapView/index.tsx
  src/config/indonesia/layers.json
  src/config/layers.json
  src/config/prism.json
  src/config/types.ts
  src/utils/server-utils.ts
Labels: frontend, skills:React
