Repository WFP-VAM/prism-app, pull requests merged in 2021-04, with the labels that each got.

#129 Use accordion menu on mobile
  package.json
  src/components/NavBar/MenuItem/__snapshots__/index.test.tsx.snap
  src/components/NavBar/MenuItem/index.tsx
  src/components/NavBar/MenuItemMobile/__snapshots__/index.test.tsx.snap
  src/components/NavBar/MenuItemMobile/index.test.tsx
  src/components/NavBar/MenuItemMobile/index.tsx
  src/components/NavBar/MenuSwitch/__snapshots__/index.test.tsx.snap
  src/components/NavBar/MenuSwitch/index.test.tsx
  src/components/NavBar/MenuSwitch/index.tsx
  src/components/NavBar/__snapshots__/index.test.tsx.snap
  src/components/NavBar/index.test.tsx
  src/components/NavBar/index.tsx
  src/config/types.ts
  src/muiTheme.tsx
  yarn.lock
Labels: frontend

#155 Fetch first available date on a month switch event
  src/components/MapView/DateSelector/index.tsx
  src/components/MapView/DateSelector/utils.ts
  src/components/MapView/index.tsx
Labels: enhancement, frontend, priority:high, skills:React

#154 Ignore secondary layers available dates
  src/components/MapView/Layers/WMSLayer/index.tsx
  src/components/MapView/index.tsx
  src/config/mozambique/layers.json
  src/utils/useDefaultDate.ts
Labels: frontend, skills:GIS, skills:React

#131 Export map as image
  package.json
  src/components/MapView/Analyser/__snapshots__/index.test.tsx.snap
  src/components/MapView/Analyser/index.tsx
  src/components/MapView/Download/__snapshots__/index.test.tsx.snap
  src/components/MapView/Download/index.test.tsx
  src/components/MapView/Download/index.tsx
  src/components/MapView/Legends/__snapshots__/index.test.tsx.snap
  src/components/MapView/Legends/index.tsx
  src/components/MapView/__snapshots__/index.test.tsx.snap
  src/components/MapView/index.test.tsx
  src/components/MapView/index.tsx
  src/setupTests.tsx
  yarn.lock
Labels: enhancement, frontend

#161 Display layer group name in navbar and independent layers for analysis
  src/components/NavBar/MenuSwitch/index.tsx
  src/config/mozambique/layers.json
  src/config/mozambique/prism.json
  src/context/mapStateSlice/index.ts
Labels: enhancement, frontend, skills:React, skills:UX

#166 Ability to fetch legend for WMS layers from server
  src/components/MapView/Legends/index.tsx
  src/config/mozambique/layers.json
  src/utils/server-utils.ts
Labels: enhancement, frontend, skills:React, skills:UX
