Repository WFP-VAM/prism-app, pull requests merged in 2021-05, with the labels that each got.

#138 Add layer opacity setting in legend
  src/components/MapView/Layers/AnalysisLayer/index.tsx
  src/components/MapView/Layers/ImpactLayer/index.tsx
  src/components/MapView/Layers/NSOLayer/index.tsx
  src/components/MapView/Layers/PointDataLayer/index.tsx
  src/components/MapView/Legends/ColorIndicator/index.tsx
  src/components/MapView/Legends/index.tsx
  src/context/mapStateSlice/index.ts
Labels: frontend

#186 Add backend functions allowing WFS analysis
  api-flask/README.md
  api-flask/app/caching.py
  api-flask/app/main.py
  api-flask/app/tests/test_calculate.py
  api-flask/app/tests/wfs_response.json
  api-flask/app/zonal_stats.py
Labels: backend, priority:high, python, skills:GIS, skills:Python

#203 Modify cql_filter to allow 00:00:00 time values
  api-flask/app/zonal_stats.py
Labels: backend, bug, skills:GIS, skills:Python
